name: Publish Docker image
on:
  workflow_dispatch:
jobs:
  down:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: downloads remote file
        run: |
          curl -L https://github.com/Nriver/trilium-translation/releases/latest/download/trilium-cn-linux-x64-server.zip \
          && uzip trilium-cn-linux-x64-server.zip
      
      
  docker:
    runs-on: ubuntu-latest
    if: ${{success()}}
    needs: [down]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: checkout version
        run: |
          version=$(cat version)
          echo >> echo "version=$version" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/trilium:latest
            ${{ secrets.DOCKER_USERNAME }}/trilium:${{ env.version }}

